import type {
  TripKpiSnapshot,
  TripSummary,
  TripWorkspaceDetail,
} from '@/features/trips/types'

export const tripKpis: TripKpiSnapshot = {
  activeTrips: { value: '24', delta: '+4%' },
  loadingTrucks: { value: '8', suffix: 'trucks' },
  salesToday: { value: '312' },
  revenueToday: { value: '$12.4k' },
}

export const mockTrips: TripSummary[] = [
  {
    id: '1042',
    displayId: 'Trip #1042',
    status: 'active',
    timeLabel: 'Started 2h ago',
    zone: 'Hargeisa East Zone',
    driverName: 'Ali Hassan',
    vehicleLabel: 'Toyota Dyna SL-2345',
    summaryAmount: '$840',
    summaryDistance: '42km',
    borderAccent: 'primary',
  },
  {
    id: '1039',
    displayId: 'Trip #1039',
    status: 'completed',
    timeLabel: '23 Oct, 2023',
    zone: 'Burao South District',
    driverName: 'Mohamed Abdi',
    vehicleLabel: 'Hino Dutro SL-1122',
    summaryAmount: '$2,450',
    summaryDistance: '184km',
    borderAccent: 'completed',
  },
  {
    id: '1038',
    displayId: 'Trip #1038',
    status: 'delayed',
    timeLabel: '23 Oct, 2023',
    zone: 'Berbera Port Access',
    driverName: 'Ismail Farah',
    vehicleLabel: 'Isuzu FTR SL-4455',
    summaryAmount: 'Mechanical Stall',
    summaryDistance: '92km',
    borderAccent: 'delayed',
  },
  {
    id: '1045',
    displayId: 'Trip #1045',
    status: 'active',
    timeLabel: 'Started 1h 15m ago',
    zone: 'Berbera Highway',
    driverName: 'Omar Duale',
    vehicleLabel: 'Isuzu NPR SL-8812',
    summaryAmount: '$1,120',
    summaryDistance: '89km',
    borderAccent: 'primary',
    subdued: true,
  },
]

const timeline1042 = [
  {
    id: 't1',
    time: '08:00',
    title: 'Arrived at Loading Dock',
    subtitle: 'Central Warehouse - Gate 4',
    variant: 'shipping' as const,
  },
  {
    id: 't2',
    time: '08:40',
    title: 'Departed Hub',
    subtitle: 'Full load manifest confirmed',
    variant: 'depart' as const,
  },
  {
    id: 't3',
    time: '09:15',
    title: 'First Sale - Al-Baraka Super',
    subtitle: 'Registered Customer | 12 Units delivered',
    variant: 'sale' as const,
  },
  {
    id: 't4',
    time: '09:45',
    title: 'Second Sale - City Mart',
    subtitle: 'Registered Customer | 8 Units delivered',
    variant: 'sale' as const,
  },
  {
    id: 't5',
    time: '',
    title: 'In Transit',
    subtitle: 'Estimated next stop: 10 mins',
    variant: 'transit' as const,
  },
]

const inventoryDefault = [
  {
    id: 'i1',
    product: 'Water 500ml',
    opening: 200,
    loaded: 150,
    sales: 120,
    closing: 230,
    variance: 0,
  },
  {
    id: 'i2',
    product: 'Rice 25kg',
    opening: 50,
    loaded: 40,
    sales: 10,
    closing: 80,
    variance: -2,
  },
  {
    id: 'i3',
    product: 'Juice Box 1L',
    opening: 100,
    loaded: 80,
    sales: 45,
    closing: 135,
    variance: 0,
  },
]

const salesDefault = [
  {
    id: 's1',
    product: 'Water 500ml (Crate)',
    qty: '24 Units',
    amount: '$120.00',
  },
  {
    id: 's2',
    product: 'Rice 25kg (Bag)',
    qty: '10 Units',
    amount: '$450.00',
  },
  {
    id: 's3',
    product: 'Juice Box 1L',
    qty: '45 Units',
    amount: '$270.00',
  },
]

export const tripWorkspaceById: Record<string, TripWorkspaceDetail> = {
  '1042': {
    tripId: '1042',
    displayId: 'Trip #1042',
    status: 'active',
    revenue: '$1,240',
    distance: '67km',
    customers: 8,
    driverName: 'Ali Hassan',
    vehicleLabel: 'Toyota Dyna SL-2345',
    timeline: timeline1042,
    inventory: inventoryDefault,
    sales: salesDefault,
  },
  '1045': {
    tripId: '1045',
    displayId: 'Trip #1045',
    status: 'active',
    revenue: '$1,120',
    distance: '89km',
    customers: 6,
    driverName: 'Omar Duale',
    vehicleLabel: 'Isuzu NPR SL-8812',
    timeline: [
      {
        id: 'a1',
        time: '07:30',
        title: 'Pre-trip inspection complete',
        subtitle: 'Berbera depot — bay 2',
        variant: 'shipping',
      },
      {
        id: 'a2',
        time: '08:05',
        title: 'Departed Berbera Highway',
        subtitle: 'Manifest sealed | 18 stops planned',
        variant: 'depart',
      },
      {
        id: 'a3',
        time: '08:50',
        title: 'First Sale - Coastal Wholesale',
        subtitle: 'Walk-in | 6 Units delivered',
        variant: 'sale',
      },
      {
        id: 'a4',
        time: '',
        title: 'In Transit',
        subtitle: 'Estimated next stop: 25 mins',
        variant: 'transit',
      },
    ],
    inventory: inventoryDefault.map((r, i) =>
      i === 0 ? { ...r, sales: 95, closing: 255 } : r,
    ),
    sales: salesDefault,
  },
  '1039': {
    tripId: '1039',
    displayId: 'Trip #1039',
    status: 'completed',
    revenue: '$2,450',
    distance: '184km',
    customers: 14,
    driverName: 'Mohamed Abdi',
    vehicleLabel: 'Hino Dutro SL-1122',
    timeline: [
      {
        id: 'c1',
        time: '06:00',
        title: 'Loaded at Burao DC',
        subtitle: 'Full manifest — 22 SKUs',
        variant: 'shipping',
      },
      {
        id: 'c2',
        time: '11:30',
        title: 'Route complete',
        subtitle: 'All deliveries signed — POD uploaded',
        variant: 'depart',
      },
      {
        id: 'c3',
        time: '14:00',
        title: 'Returned to hub',
        subtitle: 'Vehicle inspection passed',
        variant: 'sale',
      },
    ],
    inventory: inventoryDefault,
    sales: [
      { id: 'x1', product: 'Water 500ml (Crate)', qty: '80 Units', amount: '$400.00' },
      { id: 'x2', product: 'Rice 25kg (Bag)', qty: '24 Units', amount: '$1,080.00' },
      { id: 'x3', product: 'Cooking Oil 5L', qty: '36 Units', amount: '$540.00' },
    ],
  },
  '1038': {
    tripId: '1038',
    displayId: 'Trip #1038',
    status: 'delayed',
    revenue: '$610',
    distance: '92km',
    customers: 3,
    driverName: 'Ismail Farah',
    vehicleLabel: 'Isuzu FTR SL-4455',
    timeline: [
      {
        id: 'd1',
        time: '05:45',
        title: 'Departed Berbera Port',
        subtitle: 'Cold chain load verified',
        variant: 'depart',
      },
      {
        id: 'd2',
        time: '09:20',
        title: 'Mechanical stall reported',
        subtitle: 'Highway checkpoint east — support dispatched',
        variant: 'transit',
      },
      {
        id: 'd3',
        time: '',
        title: 'Awaiting resolution',
        subtitle: 'Driver safe | ETA to resume unknown',
        variant: 'shipping',
      },
    ],
    inventory: inventoryDefault.map((r) =>
      r.id === 'i2' ? { ...r, sales: 6, variance: -4 } : r,
    ),
    sales: salesDefault.slice(0, 2),
  },
}
