import type { FleetVehicle } from '@/features/fleet/types'

export const MOCK_DRIVER_OPTIONS = [
  'Unassigned',
  'John Doe',
  'Jane Smith',
  'Alex Rivera',
  'Sam Chen',
] as const

const fuelSample = [
  {
    id: 'fh1',
    date: 'Oct 24, 2023',
    liters: '45.5 L',
    costPerLiter: '$1.82',
    totalCost: '$82.81',
    statusTone: 'success' as const,
    statusLabel: 'Approved',
  },
  {
    id: 'fh2',
    date: 'Oct 18, 2023',
    liters: '42.0 L',
    costPerLiter: '$1.80',
    totalCost: '$75.60',
    statusTone: 'success' as const,
    statusLabel: 'Approved',
  },
]

const maintSample = [
  {
    id: 'm1',
    date: 'Nov 2, 2023',
    type: 'Oil change',
    notes: 'Synthetic 5W-30, filter replaced',
    statusTone: 'success' as const,
    statusLabel: 'Complete',
  },
  {
    id: 'm2',
    date: 'Oct 12, 2023',
    type: 'Brake inspection',
    notes: 'Pads OK, rotors scheduled next quarter',
    statusTone: 'warning' as const,
    statusLabel: 'Watch',
  },
]

const inventorySample = [
  {
    id: 'inv1',
    product: 'Premium Electronics',
    quantity: '120 units',
    price: '$42,000',
  },
  {
    id: 'inv2',
    product: 'Industrial Parts',
    quantity: '45 units',
    price: '$12,500',
  },
]

export const mockFleetVehicles: FleetVehicle[] = [
  {
    id: 'v1',
    model: 'Isuzu NPR',
    plate: 'SL-2345',
    tripId: 'TR-28471',
    driverName: null,
    operationalStatus: 'active',
    capacityPercent: 72,
    fuelLiters: 72,
    fuelTankPercent: 72,
    metricVariant: 'active_full',
    volumeLabel: '300m³',
    weightLabel: '0kg',
    efficiencyLabel: '50km/L',
    fuelHistory: fuelSample,
    maintenance: maintSample,
    inventory: inventorySample,
  },
  {
    id: 'v2',
    model: 'Hino Dutro 300',
    plate: 'GD-8812',
    tripId: '—',
    driverName: null,
    operationalStatus: 'available',
    capacityPercent: 0,
    fuelLiters: 15.5,
    fuelTankPercent: 15,
    metricVariant: 'available_bars',
    volumeLabel: '0m³',
    weightLabel: '0kg',
    efficiencyLabel: '—',
    fuelHistory: fuelSample,
    maintenance: maintSample,
    inventory: inventorySample,
  },
  {
    id: 'v3',
    model: 'Mitsubishi Canter',
    plate: 'XP-4490',
    tripId: 'TR-19203',
    driverName: 'John Doe',
    operationalStatus: 'in_transit',
    capacityPercent: 34,
    fuelLiters: 45.5,
    fuelTankPercent: 45,
    metricVariant: 'loading_bars',
    volumeLabel: '24m³',
    weightLabel: '900kg',
    efficiencyLabel: '32km/L',
    fuelHistory: fuelSample,
    maintenance: maintSample,
    inventory: inventorySample,
  },
  {
    id: 'v4',
    model: 'Volvo FL',
    plate: 'MM-9901',
    tripId: '—',
    driverName: null,
    operationalStatus: 'maintenance',
    capacityPercent: 42,
    fuelLiters: 8,
    fuelTankPercent: 8,
    metricVariant: 'maintenance_bars',
    volumeLabel: '—',
    weightLabel: '—',
    efficiencyLabel: '—',
    volumeSecondary: 'Poor',
    weightSecondary: '42%',
    fuelHistory: fuelSample,
    maintenance: maintSample,
    inventory: inventorySample,
  },
  {
    id: 'v5',
    model: 'Fuso Fighter',
    plate: 'QT-2201',
    tripId: 'TR-44102',
    driverName: 'Jane Smith',
    operationalStatus: 'active',
    capacityPercent: 81,
    fuelLiters: 120,
    fuelTankPercent: 60,
    metricVariant: 'active_full',
    volumeLabel: '180m³',
    weightLabel: '2.1t',
    efficiencyLabel: '12km/L',
    fuelHistory: fuelSample,
    maintenance: maintSample,
    inventory: inventorySample,
  },
  {
    id: 'v6',
    model: 'Mercedes Atego',
    plate: 'BN-7730',
    tripId: 'TR-55190',
    driverName: 'Alex Rivera',
    operationalStatus: 'in_transit',
    capacityPercent: 55,
    fuelLiters: 88,
    fuelTankPercent: 55,
    metricVariant: 'loading_bars',
    volumeLabel: '42m³',
    weightLabel: '1.2t',
    efficiencyLabel: '28km/L',
    fuelHistory: fuelSample,
    maintenance: maintSample,
    inventory: inventorySample,
  },
  {
    id: 'v7',
    model: 'Iveco Daily',
    plate: 'KL-0098',
    tripId: '—',
    driverName: null,
    operationalStatus: 'available',
    capacityPercent: 12,
    fuelLiters: 40,
    fuelTankPercent: 40,
    metricVariant: 'available_bars',
    volumeLabel: '0m³',
    weightLabel: '0kg',
    efficiencyLabel: '—',
    fuelHistory: fuelSample,
    maintenance: maintSample,
    inventory: inventorySample,
  },
  {
    id: 'v8',
    model: 'Scania P-series',
    plate: 'ZX-6612',
    tripId: 'TR-90012',
    driverName: 'Sam Chen',
    operationalStatus: 'active',
    capacityPercent: 93,
    fuelLiters: 200,
    fuelTankPercent: 80,
    metricVariant: 'active_full',
    volumeLabel: '420m³',
    weightLabel: '8.5t',
    efficiencyLabel: '8km/L',
    fuelHistory: fuelSample,
    maintenance: maintSample,
    inventory: inventorySample,
  },
  {
    id: 'v9',
    model: 'DAF LF',
    plate: 'PP-3344',
    tripId: 'TR-77123',
    driverName: null,
    operationalStatus: 'available',
    capacityPercent: 5,
    fuelLiters: 95,
    fuelTankPercent: 48,
    metricVariant: 'available_bars',
    volumeLabel: '0m³',
    weightLabel: '0kg',
    efficiencyLabel: '—',
    fuelHistory: fuelSample,
    maintenance: maintSample,
    inventory: inventorySample,
  },
  {
    id: 'v10',
    model: 'Renault Master',
    plate: 'RR-1200',
    tripId: 'TR-33211',
    driverName: 'John Doe',
    operationalStatus: 'in_transit',
    capacityPercent: 62,
    fuelLiters: 62,
    fuelTankPercent: 62,
    metricVariant: 'loading_bars',
    volumeLabel: '18m³',
    weightLabel: '400kg',
    efficiencyLabel: '22km/L',
    fuelHistory: fuelSample,
    maintenance: maintSample,
    inventory: inventorySample,
  },
  {
    id: 'v11',
    model: 'Ford Transit',
    plate: 'FT-8899',
    tripId: '—',
    driverName: null,
    operationalStatus: 'maintenance',
    capacityPercent: 0,
    fuelLiters: 25,
    fuelTankPercent: 25,
    metricVariant: 'maintenance_bars',
    volumeLabel: '—',
    weightLabel: '—',
    efficiencyLabel: '—',
    volumeSecondary: 'Awaiting parts',
    weightSecondary: '—',
    fuelHistory: fuelSample,
    maintenance: maintSample,
    inventory: inventorySample,
  },
  {
    id: 'v12',
    model: 'Toyota Dyna',
    plate: 'TY-4455',
    tripId: 'TR-66100',
    driverName: 'Jane Smith',
    operationalStatus: 'active',
    capacityPercent: 48,
    fuelLiters: 55,
    fuelTankPercent: 50,
    metricVariant: 'active_full',
    volumeLabel: '95m³',
    weightLabel: '500kg',
    efficiencyLabel: '38km/L',
    fuelHistory: fuelSample,
    maintenance: maintSample,
    inventory: inventorySample,
  },
]

export const fleetKpis = {
  totalVehicles: mockFleetVehicles.length,
  avgCapacity: '86.4%',
  avgCapacityDelta: '+2.1%',
  avgFuelEfficiency: '14.2 km/L',
  avgFuelBadge: '↑ 5%',
}
