import type { CustomerRow, DriverRow, ProductRow, ZoneRow } from './types'

export const driverRows: DriverRow[] = [
  {
    id: 'd1',
    fullName: 'Ali Hassan',
    driverId: 'DRV-9021',
    phone: '+252 63 4455667',
    zone: 'Hargeisa East',
    vehicleModel: 'Toyota Dyna',
    plate: 'SL2345',
    status: 'Available',
  },
  {
    id: 'd2',
    fullName: 'Omar Mohamud',
    driverId: 'DRV-8842',
    phone: '+252 63 9900112',
    zone: 'Hargeisa West',
    vehicleModel: 'Isuzu NPR',
    plate: 'SL9011',
    status: 'On Trip',
  },
  {
    id: 'd3',
    fullName: 'Farah Ismail',
    driverId: 'DRV-7731',
    phone: '+252 63 1122334',
    zone: 'Hargeisa East',
    vehicleModel: 'Toyota Dyna',
    plate: 'SL7766',
    status: 'Available',
  },
  {
    id: 'd4',
    fullName: 'Sahra Abdi',
    driverId: 'DRV-6610',
    phone: '+252 63 2211009',
    zone: 'Berbera Port',
    vehicleModel: 'Mercedes Atego',
    plate: 'SL4400',
    status: 'On Trip',
  },
  {
    id: 'd5',
    fullName: 'Yusuf Ahmed',
    driverId: 'DRV-5598',
    phone: '+252 63 7788990',
    zone: 'Hargeisa West',
    vehicleModel: 'Fuso Canter',
    plate: 'SL3321',
    status: 'Available',
  },
  {
    id: 'd6',
    fullName: 'Khadija Omar',
    driverId: 'DRV-4482',
    phone: '+252 63 3344556',
    zone: 'Hargeisa East',
    vehicleModel: 'Isuzu NPR',
    plate: 'SL1199',
    status: 'Off Duty',
  },
  {
    id: 'd7',
    fullName: 'Mohamed Ali',
    driverId: 'DRV-3371',
    phone: '+252 63 6677881',
    zone: 'Burao Hub',
    vehicleModel: 'Toyota Dyna',
    plate: 'SL8822',
    status: 'Available',
  },
  {
    id: 'd8',
    fullName: 'Hodan Keyse',
    driverId: 'DRV-2290',
    phone: '+252 63 1010101',
    zone: 'Hargeisa West',
    vehicleModel: 'Mercedes Atego',
    plate: 'SL5544',
    status: 'On Trip',
  },
  {
    id: 'd9',
    fullName: 'Abdirahman Warsame',
    driverId: 'DRV-1188',
    phone: '+252 63 9090909',
    zone: 'Berbera Port',
    vehicleModel: 'Fuso Canter',
    plate: 'SL6677',
    status: 'Available',
  },
  {
    id: 'd10',
    fullName: 'Ikram Hussen',
    driverId: 'DRV-0077',
    phone: '+252 63 1212121',
    zone: 'Hargeisa East',
    vehicleModel: 'Isuzu NPR',
    plate: 'SL3001',
    status: 'Available',
  },
  {
    id: 'd11',
    fullName: 'Hamza Nur',
    driverId: 'DRV-0066',
    phone: '+252 63 3434343',
    zone: 'Burao Hub',
    vehicleModel: 'Toyota Dyna',
    plate: 'SL7112',
    status: 'Off Duty',
  },
  {
    id: 'd12',
    fullName: 'Amina Said',
    driverId: 'DRV-0055',
    phone: '+252 63 5656565',
    zone: 'Hargeisa West',
    vehicleModel: 'Mercedes Atego',
    plate: 'SL9002',
    status: 'On Trip',
  },
  {
    id: 'd13',
    fullName: 'Bashir Jama',
    driverId: 'DRV-0044',
    phone: '+252 63 7878787',
    zone: 'Hargeisa East',
    vehicleModel: 'Fuso Canter',
    plate: 'SL8120',
    status: 'Available',
  },
  {
    id: 'd14',
    fullName: 'Fadumo Elmi',
    driverId: 'DRV-0033',
    phone: '+252 63 4141414',
    zone: 'Berbera Port',
    vehicleModel: 'Isuzu NPR',
    plate: 'SL2233',
    status: 'Available',
  },
  {
    id: 'd15',
    fullName: 'Mustafe Hirsi',
    driverId: 'DRV-0022',
    phone: '+252 63 6363636',
    zone: 'Burao Hub',
    vehicleModel: 'Toyota Dyna',
    plate: 'SL5050',
    status: 'On Trip',
  },
  {
    id: 'd16',
    fullName: 'Ladan Osman',
    driverId: 'DRV-0011',
    phone: '+252 63 8585858',
    zone: 'Hargeisa West',
    vehicleModel: 'Mercedes Atego',
    plate: 'SL6061',
    status: 'Off Duty',
  },
  {
    id: 'd17',
    fullName: 'Guled Farah',
    driverId: 'DRV-0009',
    phone: '+252 63 2727272',
    zone: 'Hargeisa East',
    vehicleModel: 'Fuso Canter',
    plate: 'SL1441',
    status: 'Available',
  },
  {
    id: 'd18',
    fullName: 'Raho Mohamud',
    driverId: 'DRV-0008',
    phone: '+252 63 4949494',
    zone: 'Hargeisa West',
    vehicleModel: 'Isuzu NPR',
    plate: 'SL9880',
    status: 'Available',
  },
]

export const productRows: ProductRow[] = [
  {
    id: 'p1',
    name: 'Premium Bottled Water (24pk)',
    type: 'Beverage',
    price: '$18.50',
    unitWeight: '12.4 kg',
    unitVolume: '0.028 m³',
  },
  {
    id: 'p2',
    name: 'Fortified Cooking Oil (5L)',
    type: 'Grocery',
    price: '$22.00',
    unitWeight: '5.1 kg',
    unitVolume: '0.006 m³',
  },
  {
    id: 'p3',
    name: 'Cold Chain Dairy Crate',
    type: 'Perishable',
    price: '$34.75',
    unitWeight: '18.0 kg',
    unitVolume: '0.045 m³',
  },
  {
    id: 'p4',
    name: 'Bulk Maize Sack (50kg)',
    type: 'Grain',
    price: '$41.20',
    unitWeight: '50.0 kg',
    unitVolume: '0.09 m³',
  },
  {
    id: 'p5',
    name: 'Hygiene Bundle (mixed)',
    type: 'Non-food',
    price: '$27.90',
    unitWeight: '8.2 kg',
    unitVolume: '0.032 m³',
  },
]

export const zoneRows: ZoneRow[] = [
  {
    id: 'z1',
    name: 'Hargeisa East',
    city: 'Hargeisa',
    stores: 28,
    assignedDrivers: 7,
    status: 'Active',
  },
  {
    id: 'z2',
    name: 'Hargeisa West',
    city: 'Hargeisa',
    stores: 22,
    assignedDrivers: 6,
    status: 'Active',
  },
  {
    id: 'z3',
    name: 'Berbera Port',
    city: 'Berbera',
    stores: 14,
    assignedDrivers: 4,
    status: 'Active',
  },
  {
    id: 'z4',
    name: 'Burao Hub',
    city: 'Burao',
    stores: 19,
    assignedDrivers: 5,
    status: 'Planning',
  },
  {
    id: 'z5',
    name: 'Borama Corridor',
    city: 'Borama',
    stores: 11,
    assignedDrivers: 3,
    status: 'Active',
  },
  {
    id: 'z6',
    name: 'Togdheer North',
    city: 'Burao',
    stores: 9,
    assignedDrivers: 2,
    status: 'Planning',
  },
]

export const customerRows: CustomerRow[] = [
  {
    id: 'c1',
    name: 'Barwaaqo Wholesale',
    phone: '+252 63 2001100',
    zone: 'Hargeisa East',
    location: 'Kaah Market',
    lastOrder: 'Apr 18, 2026',
  },
  {
    id: 'c2',
    name: 'Xeeb Retail Group',
    phone: '+252 63 3002200',
    zone: 'Hargeisa West',
    location: 'Downtown Ring',
    lastOrder: 'Apr 19, 2026',
  },
  {
    id: 'c3',
    name: 'Red Sea Mini-mart',
    phone: '+252 63 4003300',
    zone: 'Berbera Port',
    location: 'Harbor Road',
    lastOrder: 'Apr 17, 2026',
  },
  {
    id: 'c4',
    name: 'Togdheer Foods',
    phone: '+252 63 5004400',
    zone: 'Burao Hub',
    location: 'Central Plaza',
    lastOrder: 'Apr 16, 2026',
  },
  {
    id: 'c5',
    name: 'Sahil Fresh Co-op',
    phone: '+252 63 6005500',
    zone: 'Hargeisa East',
    location: 'Industrial Zone B',
    lastOrder: 'Apr 19, 2026',
  },
]
